// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azuredevops;

import com.pulumi.azuredevops.Utilities;
import com.pulumi.azuredevops.WorkitemtrackingprocessControlArgs;
import com.pulumi.azuredevops.inputs.WorkitemtrackingprocessControlState;
import com.pulumi.azuredevops.outputs.WorkitemtrackingprocessControlContribution;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a control within a group for a work item type. Controls can be field controls or contribution controls (extensions).
 * 
 * ## Example Usage
 * 
 * ### Basic Field Control
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessProcess;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessProcessArgs;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessWorkitemtype;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessWorkitemtypeArgs;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessGroup;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessGroupArgs;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessControl;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessControlArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new WorkitemtrackingprocessProcess("example", WorkitemtrackingprocessProcessArgs.builder()
 *             .name("example-process")
 *             .parentProcessTypeId("adcc42ab-9882-485e-a3ed-7678f01f66bc")
 *             .build());
 * 
 *         var exampleWorkitemtrackingprocessWorkitemtype = new WorkitemtrackingprocessWorkitemtype("exampleWorkitemtrackingprocessWorkitemtype", WorkitemtrackingprocessWorkitemtypeArgs.builder()
 *             .processId(example.id())
 *             .name("example")
 *             .build());
 * 
 *         var exampleWorkitemtrackingprocessGroup = new WorkitemtrackingprocessGroup("exampleWorkitemtrackingprocessGroup", WorkitemtrackingprocessGroupArgs.builder()
 *             .processId(example.id())
 *             .workItemTypeReferenceName(exampleWorkitemtrackingprocessWorkitemtype.referenceName())
 *             .pageId(exampleWorkitemtrackingprocessWorkitemtype.pages().applyValue(_pages -> _pages[0].id()))
 *             .sectionId(exampleWorkitemtrackingprocessWorkitemtype.pages().applyValue(_pages -> _pages[0].sections()[0].id()))
 *             .label("Custom Group")
 *             .build());
 * 
 *         var exampleWorkitemtrackingprocessControl = new WorkitemtrackingprocessControl("exampleWorkitemtrackingprocessControl", WorkitemtrackingprocessControlArgs.builder()
 *             .processId(example.id())
 *             .workItemTypeReferenceName(exampleWorkitemtrackingprocessWorkitemtype.referenceName())
 *             .groupId(exampleWorkitemtrackingprocessGroup.id())
 *             .controlId("System.Title")
 *             .label("Title")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ### Contribution Control (Extension)
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessProcess;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessProcessArgs;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessWorkitemtype;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessWorkitemtypeArgs;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessGroup;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessGroupArgs;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessControl;
 * import com.pulumi.azuredevops.WorkitemtrackingprocessControlArgs;
 * import com.pulumi.azuredevops.inputs.WorkitemtrackingprocessControlContributionArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new WorkitemtrackingprocessProcess("example", WorkitemtrackingprocessProcessArgs.builder()
 *             .name("example-process")
 *             .parentProcessTypeId("adcc42ab-9882-485e-a3ed-7678f01f66bc")
 *             .build());
 * 
 *         var exampleWorkitemtrackingprocessWorkitemtype = new WorkitemtrackingprocessWorkitemtype("exampleWorkitemtrackingprocessWorkitemtype", WorkitemtrackingprocessWorkitemtypeArgs.builder()
 *             .processId(example.id())
 *             .name("example")
 *             .build());
 * 
 *         var exampleWorkitemtrackingprocessGroup = new WorkitemtrackingprocessGroup("exampleWorkitemtrackingprocessGroup", WorkitemtrackingprocessGroupArgs.builder()
 *             .processId(example.id())
 *             .workItemTypeReferenceName(exampleWorkitemtrackingprocessWorkitemtype.referenceName())
 *             .pageId(exampleWorkitemtrackingprocessWorkitemtype.pages().applyValue(_pages -> _pages[0].id()))
 *             .sectionId(exampleWorkitemtrackingprocessWorkitemtype.pages().applyValue(_pages -> _pages[0].sections()[0].id()))
 *             .label("Custom Group")
 *             .build());
 * 
 *         var exampleWorkitemtrackingprocessControl = new WorkitemtrackingprocessControl("exampleWorkitemtrackingprocessControl", WorkitemtrackingprocessControlArgs.builder()
 *             .processId(example.id())
 *             .workItemTypeReferenceName(exampleWorkitemtrackingprocessWorkitemtype.referenceName())
 *             .groupId(exampleWorkitemtrackingprocessGroup.id())
 *             .controlId("MultiValueControl")
 *             .isContribution(true)
 *             .contribution(WorkitemtrackingprocessControlContributionArgs.builder()
 *                 .contributionId("ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control")
 *                 .height(50)
 *                 .inputs(Map.ofEntries(
 *                     Map.entry("FieldName", "System.Tags"),
 *                     Map.entry("Values", "Option1;Option2;Option3")
 *                 ))
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Relevant Links
 * 
 * - [Azure DevOps Service REST API 7.1 - Controls](https://learn.microsoft.com/en-us/rest/api/azure/devops/processes/controls?view=azure-devops-rest-7.1)
 * 
 * ## Import
 * 
 * Controls can be imported using the complete resource id `process_id/work_item_type_reference_name/group_id/control_id`, e.g.
 * 
 * ```sh
 * $ pulumi import azuredevops:index/workitemtrackingprocessControl:WorkitemtrackingprocessControl example 00000000-0000-0000-0000-000000000000/MyProcess.CustomWorkItemType/group-id/System.Title
 * ```
 * 
 */
@ResourceType(type="azuredevops:index/workitemtrackingprocessControl:WorkitemtrackingprocessControl")
public class WorkitemtrackingprocessControl extends com.pulumi.resources.CustomResource {
    /**
     * Contribution configuration for extension controls. A `contribution` block as defined below.
     * 
     */
    @Export(name="contribution", refs={WorkitemtrackingprocessControlContribution.class}, tree="[0]")
    private Output</* @Nullable */ WorkitemtrackingprocessControlContribution> contribution;

    /**
     * @return Contribution configuration for extension controls. A `contribution` block as defined below.
     * 
     */
    public Output<Optional<WorkitemtrackingprocessControlContribution>> contribution() {
        return Codegen.optional(this.contribution);
    }
    /**
     * The ID for the control. For field controls, this is the field reference name. Changing this forces a new control to be created.
     * 
     */
    @Export(name="controlId", refs={String.class}, tree="[0]")
    private Output<String> controlId;

    /**
     * @return The ID for the control. For field controls, this is the field reference name. Changing this forces a new control to be created.
     * 
     */
    public Output<String> controlId() {
        return this.controlId;
    }
    /**
     * The type of the control (e.g., FieldControl, HtmlFieldControl, DateTimeControl).
     * 
     */
    @Export(name="controlType", refs={String.class}, tree="[0]")
    private Output<String> controlType;

    /**
     * @return The type of the control (e.g., FieldControl, HtmlFieldControl, DateTimeControl).
     * 
     */
    public Output<String> controlType() {
        return this.controlType;
    }
    /**
     * The ID of the group to add the control to. Changing this moves the control to the new group.
     * 
     */
    @Export(name="groupId", refs={String.class}, tree="[0]")
    private Output<String> groupId;

    /**
     * @return The ID of the group to add the control to. Changing this moves the control to the new group.
     * 
     */
    public Output<String> groupId() {
        return this.groupId;
    }
    /**
     * A value indicating whether this layout node has been inherited from a parent layout.
     * 
     */
    @Export(name="inherited", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> inherited;

    /**
     * @return A value indicating whether this layout node has been inherited from a parent layout.
     * 
     */
    public Output<Boolean> inherited() {
        return this.inherited;
    }
    /**
     * A value indicating if the control is a contribution (extension) control. Default: `false`
     * 
     */
    @Export(name="isContribution", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> isContribution;

    /**
     * @return A value indicating if the control is a contribution (extension) control. Default: `false`
     * 
     */
    public Output<Optional<Boolean>> isContribution() {
        return Codegen.optional(this.isContribution);
    }
    /**
     * Label for the control.
     * 
     */
    @Export(name="label", refs={String.class}, tree="[0]")
    private Output<String> label;

    /**
     * @return Label for the control.
     * 
     */
    public Output<String> label() {
        return this.label;
    }
    /**
     * Inner text of the control.
     * 
     */
    @Export(name="metadata", refs={String.class}, tree="[0]")
    private Output<String> metadata;

    /**
     * @return Inner text of the control.
     * 
     */
    public Output<String> metadata() {
        return this.metadata;
    }
    /**
     * Order in which the control should appear in its group.
     * 
     */
    @Export(name="order", refs={Integer.class}, tree="[0]")
    private Output<Integer> order;

    /**
     * @return Order in which the control should appear in its group.
     * 
     */
    public Output<Integer> order() {
        return this.order;
    }
    /**
     * A value indicating whether this layout node has been overridden by a child layout.
     * 
     */
    @Export(name="overridden", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> overridden;

    /**
     * @return A value indicating whether this layout node has been overridden by a child layout.
     * 
     */
    public Output<Boolean> overridden() {
        return this.overridden;
    }
    /**
     * The ID of the process. Changing this forces a new control to be created.
     * 
     */
    @Export(name="processId", refs={String.class}, tree="[0]")
    private Output<String> processId;

    /**
     * @return The ID of the process. Changing this forces a new control to be created.
     * 
     */
    public Output<String> processId() {
        return this.processId;
    }
    /**
     * A value indicating if the control is readonly. Default: `false`
     * 
     */
    @Export(name="readOnly", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> readOnly;

    /**
     * @return A value indicating if the control is readonly. Default: `false`
     * 
     */
    public Output<Optional<Boolean>> readOnly() {
        return Codegen.optional(this.readOnly);
    }
    /**
     * A value indicating if the control should be visible or not. Default: `true`
     * 
     */
    @Export(name="visible", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> visible;

    /**
     * @return A value indicating if the control should be visible or not. Default: `true`
     * 
     */
    public Output<Optional<Boolean>> visible() {
        return Codegen.optional(this.visible);
    }
    /**
     * Watermark text for the textbox.
     * 
     */
    @Export(name="watermark", refs={String.class}, tree="[0]")
    private Output<String> watermark;

    /**
     * @return Watermark text for the textbox.
     * 
     */
    public Output<String> watermark() {
        return this.watermark;
    }
    /**
     * The reference name of the work item type. Changing this forces a new control to be created.
     * 
     */
    @Export(name="workItemTypeReferenceName", refs={String.class}, tree="[0]")
    private Output<String> workItemTypeReferenceName;

    /**
     * @return The reference name of the work item type. Changing this forces a new control to be created.
     * 
     */
    public Output<String> workItemTypeReferenceName() {
        return this.workItemTypeReferenceName;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public WorkitemtrackingprocessControl(java.lang.String name) {
        this(name, WorkitemtrackingprocessControlArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public WorkitemtrackingprocessControl(java.lang.String name, WorkitemtrackingprocessControlArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public WorkitemtrackingprocessControl(java.lang.String name, WorkitemtrackingprocessControlArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("azuredevops:index/workitemtrackingprocessControl:WorkitemtrackingprocessControl", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private WorkitemtrackingprocessControl(java.lang.String name, Output<java.lang.String> id, @Nullable WorkitemtrackingprocessControlState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("azuredevops:index/workitemtrackingprocessControl:WorkitemtrackingprocessControl", name, state, makeResourceOptions(options, id), false);
    }

    private static WorkitemtrackingprocessControlArgs makeArgs(WorkitemtrackingprocessControlArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? WorkitemtrackingprocessControlArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static WorkitemtrackingprocessControl get(java.lang.String name, Output<java.lang.String> id, @Nullable WorkitemtrackingprocessControlState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new WorkitemtrackingprocessControl(name, id, state, options);
    }
}
