// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azuredevops.Pipeline.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class VariableGroupKeyVault {
    /**
     * @return The name of the Azure key vault to link secrets from as variables.
     * 
     */
    private String name;
    /**
     * @return Set the Azure Key Vault Secret search depth. Defaults to `20`.
     * 
     */
    private @Nullable Integer searchDepth;
    /**
     * @return The id of the Azure subscription endpoint to access the key vault.
     * 
     */
    private String serviceEndpointId;

    private VariableGroupKeyVault() {}
    /**
     * @return The name of the Azure key vault to link secrets from as variables.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Set the Azure Key Vault Secret search depth. Defaults to `20`.
     * 
     */
    public Optional<Integer> searchDepth() {
        return Optional.ofNullable(this.searchDepth);
    }
    /**
     * @return The id of the Azure subscription endpoint to access the key vault.
     * 
     */
    public String serviceEndpointId() {
        return this.serviceEndpointId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(VariableGroupKeyVault defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        private @Nullable Integer searchDepth;
        private String serviceEndpointId;
        public Builder() {}
        public Builder(VariableGroupKeyVault defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.searchDepth = defaults.searchDepth;
    	      this.serviceEndpointId = defaults.serviceEndpointId;
        }

        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("VariableGroupKeyVault", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder searchDepth(@Nullable Integer searchDepth) {

            this.searchDepth = searchDepth;
            return this;
        }
        @CustomType.Setter
        public Builder serviceEndpointId(String serviceEndpointId) {
            if (serviceEndpointId == null) {
              throw new MissingRequiredPropertyException("VariableGroupKeyVault", "serviceEndpointId");
            }
            this.serviceEndpointId = serviceEndpointId;
            return this;
        }
        public VariableGroupKeyVault build() {
            final var _resultValue = new VariableGroupKeyVault();
            _resultValue.name = name;
            _resultValue.searchDepth = searchDepth;
            _resultValue.serviceEndpointId = serviceEndpointId;
            return _resultValue;
        }
    }
}
