provider: azuredevops
major-version: 3
esc:
    enabled: true
env:
    AZDO_ORG_SERVICE_URL: ${{ secrets.AZDO_ORG_SERVICE_URL }}
    AZDO_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZDO_PERSONAL_ACCESS_TOKEN }}
makeTemplate: bridged
checkoutSubmodules: true
pulumiConvert: 1
registryDocs: true
