provider: azuredevops
major-version: 3
env:
  AZDO_ORG_SERVICE_URL: ${{ secrets.AZDO_ORG_SERVICE_URL }}
  AZDO_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZDO_PERSONAL_ACCESS_TOKEN }}
makeTemplate: bridged
checkoutSubmodules: true
actions:
  preTest:
    - name: Make upstream
      run: make upstream
plugins:
  - name: azure
    version: "5.66.1"
