provider: azuredevops
lint: false
env:
  AZDO_ORG_SERVICE_URL: ${{ secrets.AZDO_ORG_SERVICE_URL }}
  AZDO_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZDO_PERSONAL_ACCESS_TOKEN }}
makeTemplate: bridged
javaGenVersion: "v0.9.8"
