// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azuredevops.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetSecurityNamespaceArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSecurityNamespaceArgs Empty = new GetSecurityNamespaceArgs();

    /**
     * The ID of the security namespace.
     * 
     * &gt; **NOTE:** One of `name` or `id` must be specified.
     * 
     */
    @Import(name="id")
    private @Nullable Output<String> id;

    /**
     * @return The ID of the security namespace.
     * 
     * &gt; **NOTE:** One of `name` or `id` must be specified.
     * 
     */
    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The name of the security namespace.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the security namespace.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private GetSecurityNamespaceArgs() {}

    private GetSecurityNamespaceArgs(GetSecurityNamespaceArgs $) {
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSecurityNamespaceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSecurityNamespaceArgs $;

        public Builder() {
            $ = new GetSecurityNamespaceArgs();
        }

        public Builder(GetSecurityNamespaceArgs defaults) {
            $ = new GetSecurityNamespaceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of the security namespace.
         * 
         * &gt; **NOTE:** One of `name` or `id` must be specified.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The ID of the security namespace.
         * 
         * &gt; **NOTE:** One of `name` or `id` must be specified.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param name The name of the security namespace.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the security namespace.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public GetSecurityNamespaceArgs build() {
            return $;
        }
    }

}
