// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureDevOps
{
    /// <summary>
    /// Manages a Maven service endpoint within Azure DevOps, which can be used as a resource in YAML pipelines to connect to a Maven instance.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using AzureDevOps = Pulumi.AzureDevOps;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var exampleProject = new AzureDevOps.Project("exampleProject", new()
    ///     {
    ///         Visibility = "private",
    ///         VersionControl = "Git",
    ///         WorkItemTemplate = "Agile",
    ///         Description = "Managed by Terraform",
    ///     });
    /// 
    ///     var exampleServiceendpointMaven = new AzureDevOps.ServiceendpointMaven("exampleServiceendpointMaven", new()
    ///     {
    ///         ProjectId = exampleProject.Id,
    ///         ServiceEndpointName = "maven-example",
    ///         Description = "Service Endpoint for 'Maven' (Managed by Terraform)",
    ///         Url = "https://example.com",
    ///         RepositoryId = "example",
    ///         AuthenticationToken = new AzureDevOps.Inputs.ServiceendpointMavenAuthenticationTokenArgs
    ///         {
    ///             Token = "0000000000000000000000000000000000000000",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// Alternatively a username and password may be used.
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using AzureDevOps = Pulumi.AzureDevOps;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var exampleProject = new AzureDevOps.Project("exampleProject", new()
    ///     {
    ///         Visibility = "private",
    ///         VersionControl = "Git",
    ///         WorkItemTemplate = "Agile",
    ///         Description = "Managed by Terraform",
    ///     });
    /// 
    ///     var exampleServiceendpointMaven = new AzureDevOps.ServiceendpointMaven("exampleServiceendpointMaven", new()
    ///     {
    ///         ProjectId = exampleProject.Id,
    ///         ServiceEndpointName = "maven-example",
    ///         Description = "Service Endpoint for 'Maven' (Managed by Terraform)",
    ///         Url = "https://example.com",
    ///         RepositoryId = "example",
    ///         AuthenticationBasic = new AzureDevOps.Inputs.ServiceendpointMavenAuthenticationBasicArgs
    ///         {
    ///             Username = "username",
    ///             Password = "password",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Service Connection Maven can be imported using the `projectId/id` or or `projectName/id`, e.g.
    /// 
    /// ```sh
    /// $ pulumi import azuredevops:index/serviceendpointMaven:ServiceendpointMaven example projectName/00000000-0000-0000-0000-000000000000
    /// ```
    /// </summary>
    [AzureDevOpsResourceType("azuredevops:index/serviceendpointMaven:ServiceendpointMaven")]
    public partial class ServiceendpointMaven : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A `authentication_basic` block as documented below.
        /// </summary>
        [Output("authenticationBasic")]
        public Output<Outputs.ServiceendpointMavenAuthenticationBasic?> AuthenticationBasic { get; private set; } = null!;

        /// <summary>
        /// A `authentication_token` block as documented below.
        /// </summary>
        [Output("authenticationToken")]
        public Output<Outputs.ServiceendpointMavenAuthenticationToken?> AuthenticationToken { get; private set; } = null!;

        [Output("authorization")]
        public Output<ImmutableDictionary<string, string>> Authorization { get; private set; } = null!;

        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The ID of the project. Changing this forces a new Service Connection Maven to be created.
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        /// <summary>
        /// The ID of the server that matches the id element of the `repository/mirror` that Maven tries to connect to.
        /// </summary>
        [Output("repositoryId")]
        public Output<string> RepositoryId { get; private set; } = null!;

        /// <summary>
        /// The name of the service endpoint. Changing this forces a new Service Connection Maven to be created.
        /// </summary>
        [Output("serviceEndpointName")]
        public Output<string> ServiceEndpointName { get; private set; } = null!;

        /// <summary>
        /// The URL of the Maven Repository.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a ServiceendpointMaven resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServiceendpointMaven(string name, ServiceendpointMavenArgs args, CustomResourceOptions? options = null)
            : base("azuredevops:index/serviceendpointMaven:ServiceendpointMaven", name, args ?? new ServiceendpointMavenArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ServiceendpointMaven(string name, Input<string> id, ServiceendpointMavenState? state = null, CustomResourceOptions? options = null)
            : base("azuredevops:index/serviceendpointMaven:ServiceendpointMaven", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServiceendpointMaven resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServiceendpointMaven Get(string name, Input<string> id, ServiceendpointMavenState? state = null, CustomResourceOptions? options = null)
        {
            return new ServiceendpointMaven(name, id, state, options);
        }
    }

    public sealed class ServiceendpointMavenArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A `authentication_basic` block as documented below.
        /// </summary>
        [Input("authenticationBasic")]
        public Input<Inputs.ServiceendpointMavenAuthenticationBasicArgs>? AuthenticationBasic { get; set; }

        /// <summary>
        /// A `authentication_token` block as documented below.
        /// </summary>
        [Input("authenticationToken")]
        public Input<Inputs.ServiceendpointMavenAuthenticationTokenArgs>? AuthenticationToken { get; set; }

        [Input("authorization")]
        private InputMap<string>? _authorization;
        public InputMap<string> Authorization
        {
            get => _authorization ?? (_authorization = new InputMap<string>());
            set => _authorization = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The ID of the project. Changing this forces a new Service Connection Maven to be created.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// The ID of the server that matches the id element of the `repository/mirror` that Maven tries to connect to.
        /// </summary>
        [Input("repositoryId", required: true)]
        public Input<string> RepositoryId { get; set; } = null!;

        /// <summary>
        /// The name of the service endpoint. Changing this forces a new Service Connection Maven to be created.
        /// </summary>
        [Input("serviceEndpointName", required: true)]
        public Input<string> ServiceEndpointName { get; set; } = null!;

        /// <summary>
        /// The URL of the Maven Repository.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public ServiceendpointMavenArgs()
        {
        }
        public static new ServiceendpointMavenArgs Empty => new ServiceendpointMavenArgs();
    }

    public sealed class ServiceendpointMavenState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A `authentication_basic` block as documented below.
        /// </summary>
        [Input("authenticationBasic")]
        public Input<Inputs.ServiceendpointMavenAuthenticationBasicGetArgs>? AuthenticationBasic { get; set; }

        /// <summary>
        /// A `authentication_token` block as documented below.
        /// </summary>
        [Input("authenticationToken")]
        public Input<Inputs.ServiceendpointMavenAuthenticationTokenGetArgs>? AuthenticationToken { get; set; }

        [Input("authorization")]
        private InputMap<string>? _authorization;
        public InputMap<string> Authorization
        {
            get => _authorization ?? (_authorization = new InputMap<string>());
            set => _authorization = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The ID of the project. Changing this forces a new Service Connection Maven to be created.
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        /// <summary>
        /// The ID of the server that matches the id element of the `repository/mirror` that Maven tries to connect to.
        /// </summary>
        [Input("repositoryId")]
        public Input<string>? RepositoryId { get; set; }

        /// <summary>
        /// The name of the service endpoint. Changing this forces a new Service Connection Maven to be created.
        /// </summary>
        [Input("serviceEndpointName")]
        public Input<string>? ServiceEndpointName { get; set; }

        /// <summary>
        /// The URL of the Maven Repository.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public ServiceendpointMavenState()
        {
        }
        public static new ServiceendpointMavenState Empty => new ServiceendpointMavenState();
    }
}
