// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureDevOps
{
    /// <summary>
    /// Manages a work item type for a process.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using AzureDevOps = Pulumi.AzureDevOps;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new AzureDevOps.WorkitemtrackingprocessProcess("example", new()
    ///     {
    ///         Name = "example-process",
    ///         ParentProcessTypeId = "adcc42ab-9882-485e-a3ed-7678f01f66bc",
    ///     });
    /// 
    ///     var exampleWorkitemtrackingprocessWorkitemtype = new AzureDevOps.WorkitemtrackingprocessWorkitemtype("example", new()
    ///     {
    ///         ProcessId = example.Id,
    ///         Name = "example",
    ///         Description = "Example work item type",
    ///         Color = "#FF5733",
    ///         Icon = "icon_clipboard",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Relevant Links
    /// 
    /// - [Azure DevOps Service REST API 7.1 - Work Item Types](https://learn.microsoft.com/en-us/rest/api/azure/devops/processes/work-item-types?view=azure-devops-rest-7.1)
    /// 
    /// ## Import
    /// 
    /// work item types can be imported using the complete resource id `process_id/reference_name`, e.g.
    /// 
    /// ```sh
    /// $ pulumi import azuredevops:index/workitemtrackingprocessWorkitemtype:WorkitemtrackingprocessWorkitemtype example 00000000-0000-0000-0000-000000000000/MyProcess.CustomWorkItemType
    /// ```
    /// </summary>
    [AzureDevOpsResourceType("azuredevops:index/workitemtrackingprocessWorkitemtype:WorkitemtrackingprocessWorkitemtype")]
    public partial class WorkitemtrackingprocessWorkitemtype : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Color hexadecimal code to represent the work item type. Default: "#009ccc"
        /// </summary>
        [Output("color")]
        public Output<string?> Color { get; private set; } = null!;

        /// <summary>
        /// Description of the work item type.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Icon to represent the work item type. Default: "IconClipboard"
        /// </summary>
        [Output("icon")]
        public Output<string?> Icon { get; private set; } = null!;

        /// <summary>
        /// True if the work item type is enabled. Default: true
        /// </summary>
        [Output("isEnabled")]
        public Output<bool?> IsEnabled { get; private set; } = null!;

        /// <summary>
        /// Name of work item type. Changing this forces a new work item type to be created.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// A `Pages` block as defined below.
        /// </summary>
        [Output("pages")]
        public Output<ImmutableArray<Outputs.WorkitemtrackingprocessWorkitemtypePage>> Pages { get; private set; } = null!;

        /// <summary>
        /// Reference name of the parent work item type. Changing this forces a new work item type to be created.
        /// </summary>
        [Output("parentWorkItemReferenceName")]
        public Output<string?> ParentWorkItemReferenceName { get; private set; } = null!;

        /// <summary>
        /// The ID of the process the work item type belongs to. Changing this forces a new work item type to be created.
        /// </summary>
        [Output("processId")]
        public Output<string> ProcessId { get; private set; } = null!;

        /// <summary>
        /// Reference name of the work item type.
        /// </summary>
        [Output("referenceName")]
        public Output<string> ReferenceName { get; private set; } = null!;

        /// <summary>
        /// Url of the work item type.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a WorkitemtrackingprocessWorkitemtype resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public WorkitemtrackingprocessWorkitemtype(string name, WorkitemtrackingprocessWorkitemtypeArgs args, CustomResourceOptions? options = null)
            : base("azuredevops:index/workitemtrackingprocessWorkitemtype:WorkitemtrackingprocessWorkitemtype", name, args ?? new WorkitemtrackingprocessWorkitemtypeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private WorkitemtrackingprocessWorkitemtype(string name, Input<string> id, WorkitemtrackingprocessWorkitemtypeState? state = null, CustomResourceOptions? options = null)
            : base("azuredevops:index/workitemtrackingprocessWorkitemtype:WorkitemtrackingprocessWorkitemtype", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing WorkitemtrackingprocessWorkitemtype resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static WorkitemtrackingprocessWorkitemtype Get(string name, Input<string> id, WorkitemtrackingprocessWorkitemtypeState? state = null, CustomResourceOptions? options = null)
        {
            return new WorkitemtrackingprocessWorkitemtype(name, id, state, options);
        }
    }

    public sealed class WorkitemtrackingprocessWorkitemtypeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Color hexadecimal code to represent the work item type. Default: "#009ccc"
        /// </summary>
        [Input("color")]
        public Input<string>? Color { get; set; }

        /// <summary>
        /// Description of the work item type.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Icon to represent the work item type. Default: "IconClipboard"
        /// </summary>
        [Input("icon")]
        public Input<string>? Icon { get; set; }

        /// <summary>
        /// True if the work item type is enabled. Default: true
        /// </summary>
        [Input("isEnabled")]
        public Input<bool>? IsEnabled { get; set; }

        /// <summary>
        /// Name of work item type. Changing this forces a new work item type to be created.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Reference name of the parent work item type. Changing this forces a new work item type to be created.
        /// </summary>
        [Input("parentWorkItemReferenceName")]
        public Input<string>? ParentWorkItemReferenceName { get; set; }

        /// <summary>
        /// The ID of the process the work item type belongs to. Changing this forces a new work item type to be created.
        /// </summary>
        [Input("processId", required: true)]
        public Input<string> ProcessId { get; set; } = null!;

        public WorkitemtrackingprocessWorkitemtypeArgs()
        {
        }
        public static new WorkitemtrackingprocessWorkitemtypeArgs Empty => new WorkitemtrackingprocessWorkitemtypeArgs();
    }

    public sealed class WorkitemtrackingprocessWorkitemtypeState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Color hexadecimal code to represent the work item type. Default: "#009ccc"
        /// </summary>
        [Input("color")]
        public Input<string>? Color { get; set; }

        /// <summary>
        /// Description of the work item type.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Icon to represent the work item type. Default: "IconClipboard"
        /// </summary>
        [Input("icon")]
        public Input<string>? Icon { get; set; }

        /// <summary>
        /// True if the work item type is enabled. Default: true
        /// </summary>
        [Input("isEnabled")]
        public Input<bool>? IsEnabled { get; set; }

        /// <summary>
        /// Name of work item type. Changing this forces a new work item type to be created.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("pages")]
        private InputList<Inputs.WorkitemtrackingprocessWorkitemtypePageGetArgs>? _pages;

        /// <summary>
        /// A `Pages` block as defined below.
        /// </summary>
        public InputList<Inputs.WorkitemtrackingprocessWorkitemtypePageGetArgs> Pages
        {
            get => _pages ?? (_pages = new InputList<Inputs.WorkitemtrackingprocessWorkitemtypePageGetArgs>());
            set => _pages = value;
        }

        /// <summary>
        /// Reference name of the parent work item type. Changing this forces a new work item type to be created.
        /// </summary>
        [Input("parentWorkItemReferenceName")]
        public Input<string>? ParentWorkItemReferenceName { get; set; }

        /// <summary>
        /// The ID of the process the work item type belongs to. Changing this forces a new work item type to be created.
        /// </summary>
        [Input("processId")]
        public Input<string>? ProcessId { get; set; }

        /// <summary>
        /// Reference name of the work item type.
        /// </summary>
        [Input("referenceName")]
        public Input<string>? ReferenceName { get; set; }

        /// <summary>
        /// Url of the work item type.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public WorkitemtrackingprocessWorkitemtypeState()
        {
        }
        public static new WorkitemtrackingprocessWorkitemtypeState Empty => new WorkitemtrackingprocessWorkitemtypeState();
    }
}
