// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azuredevops.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ServiceEndpointGitHubEnterpriseAuthPersonal {
    /**
     * @return The Personal Access Token for GitHub.
     * 
     */
    private String personalAccessToken;

    private ServiceEndpointGitHubEnterpriseAuthPersonal() {}
    /**
     * @return The Personal Access Token for GitHub.
     * 
     */
    public String personalAccessToken() {
        return this.personalAccessToken;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ServiceEndpointGitHubEnterpriseAuthPersonal defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String personalAccessToken;
        public Builder() {}
        public Builder(ServiceEndpointGitHubEnterpriseAuthPersonal defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.personalAccessToken = defaults.personalAccessToken;
        }

        @CustomType.Setter
        public Builder personalAccessToken(String personalAccessToken) {
            this.personalAccessToken = Objects.requireNonNull(personalAccessToken);
            return this;
        }
        public ServiceEndpointGitHubEnterpriseAuthPersonal build() {
            final var o = new ServiceEndpointGitHubEnterpriseAuthPersonal();
            o.personalAccessToken = personalAccessToken;
            return o;
        }
    }
}
