// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azuredevops.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class WorkitemtrackingprocessRuleAction {
    /**
     * @return Type of action. Valid values: `makeRequired`, `makeReadOnly`, `setDefaultValue`, `setDefaultFromClock`, `setDefaultFromField`, `copyValue`, `copyFromClock`, `copyFromCurrentUser`, `copyFromField`, `setValueToEmpty`, `copyFromServerClock`, `copyFromServerCurrentUser`, `hideTargetField`, `disallowValue`.
     * 
     */
    private String actionType;
    /**
     * @return Field (reference name) to act on.
     * 
     */
    private String targetField;
    /**
     * @return Value to set on the target field.
     * 
     */
    private @Nullable String value;

    private WorkitemtrackingprocessRuleAction() {}
    /**
     * @return Type of action. Valid values: `makeRequired`, `makeReadOnly`, `setDefaultValue`, `setDefaultFromClock`, `setDefaultFromField`, `copyValue`, `copyFromClock`, `copyFromCurrentUser`, `copyFromField`, `setValueToEmpty`, `copyFromServerClock`, `copyFromServerCurrentUser`, `hideTargetField`, `disallowValue`.
     * 
     */
    public String actionType() {
        return this.actionType;
    }
    /**
     * @return Field (reference name) to act on.
     * 
     */
    public String targetField() {
        return this.targetField;
    }
    /**
     * @return Value to set on the target field.
     * 
     */
    public Optional<String> value() {
        return Optional.ofNullable(this.value);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WorkitemtrackingprocessRuleAction defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String actionType;
        private String targetField;
        private @Nullable String value;
        public Builder() {}
        public Builder(WorkitemtrackingprocessRuleAction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.actionType = defaults.actionType;
    	      this.targetField = defaults.targetField;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder actionType(String actionType) {
            if (actionType == null) {
              throw new MissingRequiredPropertyException("WorkitemtrackingprocessRuleAction", "actionType");
            }
            this.actionType = actionType;
            return this;
        }
        @CustomType.Setter
        public Builder targetField(String targetField) {
            if (targetField == null) {
              throw new MissingRequiredPropertyException("WorkitemtrackingprocessRuleAction", "targetField");
            }
            this.targetField = targetField;
            return this;
        }
        @CustomType.Setter
        public Builder value(@Nullable String value) {

            this.value = value;
            return this;
        }
        public WorkitemtrackingprocessRuleAction build() {
            final var _resultValue = new WorkitemtrackingprocessRuleAction();
            _resultValue.actionType = actionType;
            _resultValue.targetField = targetField;
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
