// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package azuredevops

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azuredevops/sdk/v3/go/azuredevops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to query a specific service endpoint type and retrieve its parameters and authorization schemes.
//
// ## Example Usage
//
// ### Basic usage - Get service endpoint type information
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-azuredevops/sdk/v3/go/azuredevops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			generic, err := azuredevops.GetServiceendpointType(ctx, &azuredevops.GetServiceendpointTypeArgs{
//				Name: "generic",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("genericTypeInfo", pulumi.Map{
//				"displayName": generic.DisplayName,
//				"authSchemes": generic.AuthenticationSchemes,
//				"parameters":  generic.Parameters,
//			})
//			return nil
//		})
//	}
//
// ```
//
// ### Get authorization parameters for a specific auth scheme
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-azuredevops/sdk/v3/go/azuredevops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			generic, err := azuredevops.GetServiceendpointType(ctx, &azuredevops.GetServiceendpointTypeArgs{
//				Name:                "generic",
//				AuthorizationScheme: pulumi.StringRef("UsernamePassword"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("authParameters", generic.AuthorizationParameters)
//			return nil
//		})
//	}
//
// ```
//
// ### Use in service endpoint resource
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-azuredevops/sdk/v3/go/azuredevops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			bitbucket, err := azuredevops.GetServiceendpointType(ctx, &azuredevops.GetServiceendpointTypeArgs{
//				Name:                "bitbucket",
//				AuthorizationScheme: pulumi.StringRef("UsernamePassword"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			example, err := azuredevops.NewProject(ctx, "example", &azuredevops.ProjectArgs{
//				Name: pulumi.String("Example Project"),
//			})
//			if err != nil {
//				return err
//			}
//			// Use the data source to understand available parameters
//			_, err = azuredevops.NewServiceendpointGenericV2(ctx, "example", &azuredevops.ServiceendpointGenericV2Args{
//				ProjectId:           example.ID().ToIDOutput().ToStringOutput(),
//				Name:                pulumi.String("Example Bitbucket"),
//				Description:         pulumi.String("Managed by Pulumi"),
//				Type:                pulumi.String(bitbucket.Name),
//				ServerUrl:           pulumi.String("https://bitbucket.org"),
//				AuthorizationScheme: pulumi.String(bitbucket.AuthorizationScheme),
//				AuthorizationParameters: pulumi.StringMap{
//					"username": pulumi.String("my-username"),
//					"password": pulumi.String("my-password"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Relevant Links
//
// - [Azure DevOps Service REST API 7.0 - Service Endpoint Types](https://learn.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/types/list)
func GetServiceendpointType(ctx *pulumi.Context, args *GetServiceendpointTypeArgs, opts ...pulumi.InvokeOption) (*GetServiceendpointTypeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetServiceendpointTypeResult
	err := ctx.Invoke("azuredevops:index/getServiceendpointType:getServiceendpointType", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServiceendpointType.
type GetServiceendpointTypeArgs struct {
	// The authorization scheme to retrieve parameters for. When provided, the `authorizationParameters` output will be populated with the parameters specific to this authentication scheme.
	AuthorizationScheme *string `pulumi:"authorizationScheme"`
	// The name of the service endpoint type to query.
	Name string `pulumi:"name"`
}

// A collection of values returned by getServiceendpointType.
type GetServiceendpointTypeResult struct {
	// A list of available authentication schemes for this service endpoint type.
	AuthenticationSchemes []string `pulumi:"authenticationSchemes"`
	// A list of authorization parameter descriptors. Only populated when `authorizationScheme` is provided. Each element has:
	AuthorizationParameters []GetServiceendpointTypeAuthorizationParameter `pulumi:"authorizationParameters"`
	AuthorizationScheme     *string                                        `pulumi:"authorizationScheme"`
	// The description of the service endpoint type.
	Description string `pulumi:"description"`
	// The display name of the service endpoint type.
	DisplayName string `pulumi:"displayName"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The authorization parameter name (descriptor ID).
	Name string `pulumi:"name"`
	// A list of parameter descriptors. Each element has:
	Parameters []GetServiceendpointTypeParameter `pulumi:"parameters"`
	// The UI contribution ID for this service endpoint type.
	UiContributionId string `pulumi:"uiContributionId"`
}

func GetServiceendpointTypeOutput(ctx *pulumi.Context, args GetServiceendpointTypeOutputArgs, opts ...pulumi.InvokeOption) GetServiceendpointTypeResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetServiceendpointTypeResultOutput, error) {
			args := v.(GetServiceendpointTypeArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("azuredevops:index/getServiceendpointType:getServiceendpointType", args, GetServiceendpointTypeResultOutput{}, options).(GetServiceendpointTypeResultOutput), nil
		}).(GetServiceendpointTypeResultOutput)
}

// A collection of arguments for invoking getServiceendpointType.
type GetServiceendpointTypeOutputArgs struct {
	// The authorization scheme to retrieve parameters for. When provided, the `authorizationParameters` output will be populated with the parameters specific to this authentication scheme.
	AuthorizationScheme pulumi.StringPtrInput `pulumi:"authorizationScheme"`
	// The name of the service endpoint type to query.
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetServiceendpointTypeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServiceendpointTypeArgs)(nil)).Elem()
}

// A collection of values returned by getServiceendpointType.
type GetServiceendpointTypeResultOutput struct{ *pulumi.OutputState }

func (GetServiceendpointTypeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServiceendpointTypeResult)(nil)).Elem()
}

func (o GetServiceendpointTypeResultOutput) ToGetServiceendpointTypeResultOutput() GetServiceendpointTypeResultOutput {
	return o
}

func (o GetServiceendpointTypeResultOutput) ToGetServiceendpointTypeResultOutputWithContext(ctx context.Context) GetServiceendpointTypeResultOutput {
	return o
}

// A list of available authentication schemes for this service endpoint type.
func (o GetServiceendpointTypeResultOutput) AuthenticationSchemes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetServiceendpointTypeResult) []string { return v.AuthenticationSchemes }).(pulumi.StringArrayOutput)
}

// A list of authorization parameter descriptors. Only populated when `authorizationScheme` is provided. Each element has:
func (o GetServiceendpointTypeResultOutput) AuthorizationParameters() GetServiceendpointTypeAuthorizationParameterArrayOutput {
	return o.ApplyT(func(v GetServiceendpointTypeResult) []GetServiceendpointTypeAuthorizationParameter {
		return v.AuthorizationParameters
	}).(GetServiceendpointTypeAuthorizationParameterArrayOutput)
}

func (o GetServiceendpointTypeResultOutput) AuthorizationScheme() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetServiceendpointTypeResult) *string { return v.AuthorizationScheme }).(pulumi.StringPtrOutput)
}

// The description of the service endpoint type.
func (o GetServiceendpointTypeResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceendpointTypeResult) string { return v.Description }).(pulumi.StringOutput)
}

// The display name of the service endpoint type.
func (o GetServiceendpointTypeResultOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceendpointTypeResult) string { return v.DisplayName }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetServiceendpointTypeResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceendpointTypeResult) string { return v.Id }).(pulumi.StringOutput)
}

// The authorization parameter name (descriptor ID).
func (o GetServiceendpointTypeResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceendpointTypeResult) string { return v.Name }).(pulumi.StringOutput)
}

// A list of parameter descriptors. Each element has:
func (o GetServiceendpointTypeResultOutput) Parameters() GetServiceendpointTypeParameterArrayOutput {
	return o.ApplyT(func(v GetServiceendpointTypeResult) []GetServiceendpointTypeParameter { return v.Parameters }).(GetServiceendpointTypeParameterArrayOutput)
}

// The UI contribution ID for this service endpoint type.
func (o GetServiceendpointTypeResultOutput) UiContributionId() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceendpointTypeResult) string { return v.UiContributionId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServiceendpointTypeResultOutput{})
}
