// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package azuredevops

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-azuredevops/sdk/v3/go/azuredevops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a process.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-azuredevops/sdk/v3/go/azuredevops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := azuredevops.NewWorkitemtrackingprocessProcess(ctx, "custom_agile", &azuredevops.WorkitemtrackingprocessProcessArgs{
//				Name:                pulumi.String("custom_agile"),
//				ParentProcessTypeId: pulumi.String("adcc42ab-9882-485e-a3ed-7678f01f66bc"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Relevant Links
//
// - [Azure DevOps Service REST API 7.1 - Processes](https://learn.microsoft.com/en-us/rest/api/azure/devops/processes/processes?view=azure-devops-rest-7.1)
//
// ## Import
//
// A process can be imported using the process id, e.g.
//
// ```sh
// $ pulumi import azuredevops:index/workitemtrackingprocessProcess:WorkitemtrackingprocessProcess example 00000000-0000-0000-0000-000000000000
// ```
type WorkitemtrackingprocessProcess struct {
	pulumi.CustomResourceState

	// Indicates the type of customization on this process. System Process is default process. Inherited Process is modified process that was System process before.
	CustomizationType pulumi.StringOutput `pulumi:"customizationType"`
	// Description of the process. Default: ""
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Is the process default? Default: false
	IsDefault pulumi.BoolPtrOutput `pulumi:"isDefault"`
	// Is the process enabled? Default: true
	IsEnabled pulumi.BoolPtrOutput `pulumi:"isEnabled"`
	// Name of the process.
	Name pulumi.StringOutput `pulumi:"name"`
	// ID of the parent process. Changing this forces a new process to be created.
	ParentProcessTypeId pulumi.StringOutput `pulumi:"parentProcessTypeId"`
	// Reference name of process being created. If not specified, server will assign a unique reference name. Changing this forces a new process to be created.
	ReferenceName pulumi.StringOutput `pulumi:"referenceName"`
}

// NewWorkitemtrackingprocessProcess registers a new resource with the given unique name, arguments, and options.
func NewWorkitemtrackingprocessProcess(ctx *pulumi.Context,
	name string, args *WorkitemtrackingprocessProcessArgs, opts ...pulumi.ResourceOption) (*WorkitemtrackingprocessProcess, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ParentProcessTypeId == nil {
		return nil, errors.New("invalid value for required argument 'ParentProcessTypeId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WorkitemtrackingprocessProcess
	err := ctx.RegisterResource("azuredevops:index/workitemtrackingprocessProcess:WorkitemtrackingprocessProcess", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWorkitemtrackingprocessProcess gets an existing WorkitemtrackingprocessProcess resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWorkitemtrackingprocessProcess(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WorkitemtrackingprocessProcessState, opts ...pulumi.ResourceOption) (*WorkitemtrackingprocessProcess, error) {
	var resource WorkitemtrackingprocessProcess
	err := ctx.ReadResource("azuredevops:index/workitemtrackingprocessProcess:WorkitemtrackingprocessProcess", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WorkitemtrackingprocessProcess resources.
type workitemtrackingprocessProcessState struct {
	// Indicates the type of customization on this process. System Process is default process. Inherited Process is modified process that was System process before.
	CustomizationType *string `pulumi:"customizationType"`
	// Description of the process. Default: ""
	Description *string `pulumi:"description"`
	// Is the process default? Default: false
	IsDefault *bool `pulumi:"isDefault"`
	// Is the process enabled? Default: true
	IsEnabled *bool `pulumi:"isEnabled"`
	// Name of the process.
	Name *string `pulumi:"name"`
	// ID of the parent process. Changing this forces a new process to be created.
	ParentProcessTypeId *string `pulumi:"parentProcessTypeId"`
	// Reference name of process being created. If not specified, server will assign a unique reference name. Changing this forces a new process to be created.
	ReferenceName *string `pulumi:"referenceName"`
}

type WorkitemtrackingprocessProcessState struct {
	// Indicates the type of customization on this process. System Process is default process. Inherited Process is modified process that was System process before.
	CustomizationType pulumi.StringPtrInput
	// Description of the process. Default: ""
	Description pulumi.StringPtrInput
	// Is the process default? Default: false
	IsDefault pulumi.BoolPtrInput
	// Is the process enabled? Default: true
	IsEnabled pulumi.BoolPtrInput
	// Name of the process.
	Name pulumi.StringPtrInput
	// ID of the parent process. Changing this forces a new process to be created.
	ParentProcessTypeId pulumi.StringPtrInput
	// Reference name of process being created. If not specified, server will assign a unique reference name. Changing this forces a new process to be created.
	ReferenceName pulumi.StringPtrInput
}

func (WorkitemtrackingprocessProcessState) ElementType() reflect.Type {
	return reflect.TypeOf((*workitemtrackingprocessProcessState)(nil)).Elem()
}

type workitemtrackingprocessProcessArgs struct {
	// Description of the process. Default: ""
	Description *string `pulumi:"description"`
	// Is the process default? Default: false
	IsDefault *bool `pulumi:"isDefault"`
	// Is the process enabled? Default: true
	IsEnabled *bool `pulumi:"isEnabled"`
	// Name of the process.
	Name *string `pulumi:"name"`
	// ID of the parent process. Changing this forces a new process to be created.
	ParentProcessTypeId string `pulumi:"parentProcessTypeId"`
	// Reference name of process being created. If not specified, server will assign a unique reference name. Changing this forces a new process to be created.
	ReferenceName *string `pulumi:"referenceName"`
}

// The set of arguments for constructing a WorkitemtrackingprocessProcess resource.
type WorkitemtrackingprocessProcessArgs struct {
	// Description of the process. Default: ""
	Description pulumi.StringPtrInput
	// Is the process default? Default: false
	IsDefault pulumi.BoolPtrInput
	// Is the process enabled? Default: true
	IsEnabled pulumi.BoolPtrInput
	// Name of the process.
	Name pulumi.StringPtrInput
	// ID of the parent process. Changing this forces a new process to be created.
	ParentProcessTypeId pulumi.StringInput
	// Reference name of process being created. If not specified, server will assign a unique reference name. Changing this forces a new process to be created.
	ReferenceName pulumi.StringPtrInput
}

func (WorkitemtrackingprocessProcessArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*workitemtrackingprocessProcessArgs)(nil)).Elem()
}

type WorkitemtrackingprocessProcessInput interface {
	pulumi.Input

	ToWorkitemtrackingprocessProcessOutput() WorkitemtrackingprocessProcessOutput
	ToWorkitemtrackingprocessProcessOutputWithContext(ctx context.Context) WorkitemtrackingprocessProcessOutput
}

func (*WorkitemtrackingprocessProcess) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkitemtrackingprocessProcess)(nil)).Elem()
}

func (i *WorkitemtrackingprocessProcess) ToWorkitemtrackingprocessProcessOutput() WorkitemtrackingprocessProcessOutput {
	return i.ToWorkitemtrackingprocessProcessOutputWithContext(context.Background())
}

func (i *WorkitemtrackingprocessProcess) ToWorkitemtrackingprocessProcessOutputWithContext(ctx context.Context) WorkitemtrackingprocessProcessOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkitemtrackingprocessProcessOutput)
}

// WorkitemtrackingprocessProcessArrayInput is an input type that accepts WorkitemtrackingprocessProcessArray and WorkitemtrackingprocessProcessArrayOutput values.
// You can construct a concrete instance of `WorkitemtrackingprocessProcessArrayInput` via:
//
//	WorkitemtrackingprocessProcessArray{ WorkitemtrackingprocessProcessArgs{...} }
type WorkitemtrackingprocessProcessArrayInput interface {
	pulumi.Input

	ToWorkitemtrackingprocessProcessArrayOutput() WorkitemtrackingprocessProcessArrayOutput
	ToWorkitemtrackingprocessProcessArrayOutputWithContext(context.Context) WorkitemtrackingprocessProcessArrayOutput
}

type WorkitemtrackingprocessProcessArray []WorkitemtrackingprocessProcessInput

func (WorkitemtrackingprocessProcessArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkitemtrackingprocessProcess)(nil)).Elem()
}

func (i WorkitemtrackingprocessProcessArray) ToWorkitemtrackingprocessProcessArrayOutput() WorkitemtrackingprocessProcessArrayOutput {
	return i.ToWorkitemtrackingprocessProcessArrayOutputWithContext(context.Background())
}

func (i WorkitemtrackingprocessProcessArray) ToWorkitemtrackingprocessProcessArrayOutputWithContext(ctx context.Context) WorkitemtrackingprocessProcessArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkitemtrackingprocessProcessArrayOutput)
}

// WorkitemtrackingprocessProcessMapInput is an input type that accepts WorkitemtrackingprocessProcessMap and WorkitemtrackingprocessProcessMapOutput values.
// You can construct a concrete instance of `WorkitemtrackingprocessProcessMapInput` via:
//
//	WorkitemtrackingprocessProcessMap{ "key": WorkitemtrackingprocessProcessArgs{...} }
type WorkitemtrackingprocessProcessMapInput interface {
	pulumi.Input

	ToWorkitemtrackingprocessProcessMapOutput() WorkitemtrackingprocessProcessMapOutput
	ToWorkitemtrackingprocessProcessMapOutputWithContext(context.Context) WorkitemtrackingprocessProcessMapOutput
}

type WorkitemtrackingprocessProcessMap map[string]WorkitemtrackingprocessProcessInput

func (WorkitemtrackingprocessProcessMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkitemtrackingprocessProcess)(nil)).Elem()
}

func (i WorkitemtrackingprocessProcessMap) ToWorkitemtrackingprocessProcessMapOutput() WorkitemtrackingprocessProcessMapOutput {
	return i.ToWorkitemtrackingprocessProcessMapOutputWithContext(context.Background())
}

func (i WorkitemtrackingprocessProcessMap) ToWorkitemtrackingprocessProcessMapOutputWithContext(ctx context.Context) WorkitemtrackingprocessProcessMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkitemtrackingprocessProcessMapOutput)
}

type WorkitemtrackingprocessProcessOutput struct{ *pulumi.OutputState }

func (WorkitemtrackingprocessProcessOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkitemtrackingprocessProcess)(nil)).Elem()
}

func (o WorkitemtrackingprocessProcessOutput) ToWorkitemtrackingprocessProcessOutput() WorkitemtrackingprocessProcessOutput {
	return o
}

func (o WorkitemtrackingprocessProcessOutput) ToWorkitemtrackingprocessProcessOutputWithContext(ctx context.Context) WorkitemtrackingprocessProcessOutput {
	return o
}

// Indicates the type of customization on this process. System Process is default process. Inherited Process is modified process that was System process before.
func (o WorkitemtrackingprocessProcessOutput) CustomizationType() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkitemtrackingprocessProcess) pulumi.StringOutput { return v.CustomizationType }).(pulumi.StringOutput)
}

// Description of the process. Default: ""
func (o WorkitemtrackingprocessProcessOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkitemtrackingprocessProcess) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Is the process default? Default: false
func (o WorkitemtrackingprocessProcessOutput) IsDefault() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkitemtrackingprocessProcess) pulumi.BoolPtrOutput { return v.IsDefault }).(pulumi.BoolPtrOutput)
}

// Is the process enabled? Default: true
func (o WorkitemtrackingprocessProcessOutput) IsEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkitemtrackingprocessProcess) pulumi.BoolPtrOutput { return v.IsEnabled }).(pulumi.BoolPtrOutput)
}

// Name of the process.
func (o WorkitemtrackingprocessProcessOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkitemtrackingprocessProcess) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// ID of the parent process. Changing this forces a new process to be created.
func (o WorkitemtrackingprocessProcessOutput) ParentProcessTypeId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkitemtrackingprocessProcess) pulumi.StringOutput { return v.ParentProcessTypeId }).(pulumi.StringOutput)
}

// Reference name of process being created. If not specified, server will assign a unique reference name. Changing this forces a new process to be created.
func (o WorkitemtrackingprocessProcessOutput) ReferenceName() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkitemtrackingprocessProcess) pulumi.StringOutput { return v.ReferenceName }).(pulumi.StringOutput)
}

type WorkitemtrackingprocessProcessArrayOutput struct{ *pulumi.OutputState }

func (WorkitemtrackingprocessProcessArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkitemtrackingprocessProcess)(nil)).Elem()
}

func (o WorkitemtrackingprocessProcessArrayOutput) ToWorkitemtrackingprocessProcessArrayOutput() WorkitemtrackingprocessProcessArrayOutput {
	return o
}

func (o WorkitemtrackingprocessProcessArrayOutput) ToWorkitemtrackingprocessProcessArrayOutputWithContext(ctx context.Context) WorkitemtrackingprocessProcessArrayOutput {
	return o
}

func (o WorkitemtrackingprocessProcessArrayOutput) Index(i pulumi.IntInput) WorkitemtrackingprocessProcessOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WorkitemtrackingprocessProcess {
		return vs[0].([]*WorkitemtrackingprocessProcess)[vs[1].(int)]
	}).(WorkitemtrackingprocessProcessOutput)
}

type WorkitemtrackingprocessProcessMapOutput struct{ *pulumi.OutputState }

func (WorkitemtrackingprocessProcessMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkitemtrackingprocessProcess)(nil)).Elem()
}

func (o WorkitemtrackingprocessProcessMapOutput) ToWorkitemtrackingprocessProcessMapOutput() WorkitemtrackingprocessProcessMapOutput {
	return o
}

func (o WorkitemtrackingprocessProcessMapOutput) ToWorkitemtrackingprocessProcessMapOutputWithContext(ctx context.Context) WorkitemtrackingprocessProcessMapOutput {
	return o
}

func (o WorkitemtrackingprocessProcessMapOutput) MapIndex(k pulumi.StringInput) WorkitemtrackingprocessProcessOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WorkitemtrackingprocessProcess {
		return vs[0].(map[string]*WorkitemtrackingprocessProcess)[vs[1].(string)]
	}).(WorkitemtrackingprocessProcessOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkitemtrackingprocessProcessInput)(nil)).Elem(), &WorkitemtrackingprocessProcess{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkitemtrackingprocessProcessArrayInput)(nil)).Elem(), WorkitemtrackingprocessProcessArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkitemtrackingprocessProcessMapInput)(nil)).Elem(), WorkitemtrackingprocessProcessMap{})
	pulumi.RegisterOutputType(WorkitemtrackingprocessProcessOutput{})
	pulumi.RegisterOutputType(WorkitemtrackingprocessProcessArrayOutput{})
	pulumi.RegisterOutputType(WorkitemtrackingprocessProcessMapOutput{})
}
