# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['WorkitemqueryFolderArgs', 'WorkitemqueryFolder']

@pulumi.input_type
class WorkitemqueryFolderArgs:
    def __init__(__self__, *,
                 project_id: pulumi.Input[_builtins.str],
                 area: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 parent_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a WorkitemqueryFolder resource.
        :param pulumi.Input[_builtins.str] project_id: The ID of the Project containing the folder.
        :param pulumi.Input[_builtins.str] area: Root folder. Must be one of `Shared Queries` or `My Queries`.
        :param pulumi.Input[_builtins.str] name: The display name of the folder.
        :param pulumi.Input[_builtins.str] parent_id: The ID of the parent query folder.
        """
        pulumi.set(__self__, "project_id", project_id)
        if area is not None:
            pulumi.set(__self__, "area", area)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if parent_id is not None:
            pulumi.set(__self__, "parent_id", parent_id)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the Project containing the folder.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def area(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Root folder. Must be one of `Shared Queries` or `My Queries`.
        """
        return pulumi.get(self, "area")

    @area.setter
    def area(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "area", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The display name of the folder.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the parent query folder.
        """
        return pulumi.get(self, "parent_id")

    @parent_id.setter
    def parent_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "parent_id", value)


@pulumi.input_type
class _WorkitemqueryFolderState:
    def __init__(__self__, *,
                 area: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 parent_id: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering WorkitemqueryFolder resources.
        :param pulumi.Input[_builtins.str] area: Root folder. Must be one of `Shared Queries` or `My Queries`.
        :param pulumi.Input[_builtins.str] name: The display name of the folder.
        :param pulumi.Input[_builtins.str] parent_id: The ID of the parent query folder.
        :param pulumi.Input[_builtins.str] project_id: The ID of the Project containing the folder.
        """
        if area is not None:
            pulumi.set(__self__, "area", area)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if parent_id is not None:
            pulumi.set(__self__, "parent_id", parent_id)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)

    @_builtins.property
    @pulumi.getter
    def area(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Root folder. Must be one of `Shared Queries` or `My Queries`.
        """
        return pulumi.get(self, "area")

    @area.setter
    def area(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "area", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The display name of the folder.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the parent query folder.
        """
        return pulumi.get(self, "parent_id")

    @parent_id.setter
    def parent_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "parent_id", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the Project containing the folder.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project_id", value)


@pulumi.type_token("azuredevops:index/workitemqueryFolder:WorkitemqueryFolder")
class WorkitemqueryFolder(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 area: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 parent_id: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a Work Item Query Folder in Azure DevOps.

        Folders allow you to organize queries in a hierarchy beneath either the `Shared Queries` or `My Queries` root folder (area).
        You must provide exactly one of `area` (either `Shared Queries` or `My Queries`) or `parent_id` (an existing folder's ID) when creating a folder.

        ## Example Usage

        ### Basic folder under Shared Queries

        ```python
        import pulumi
        import pulumi_azuredevops as azuredevops

        example = azuredevops.Project("example",
            name="Example Project",
            work_item_template="Agile",
            version_control="Git",
            visibility="private",
            description="Managed by Pulumi")
        team_folder = azuredevops.WorkitemqueryFolder("team_folder",
            project_id=example.id,
            name="Team",
            area="Shared Queries")
        ```

        ### Nested folder

        ```python
        import pulumi
        import pulumi_azuredevops as azuredevops

        parent = azuredevops.WorkitemqueryFolder("parent",
            project_id=example["id"],
            name="Parent",
            area="Shared Queries")
        child = azuredevops.WorkitemqueryFolder("child",
            project_id=example["id"],
            name="Child",
            parent_id=parent.id)
        ```

        ## Relevant Links

        * [Azure DevOps REST API - Work Item Query (Queries)](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/queries?view=azure-devops-rest-7.1)

        ## PAT Permissions Required

        * **Work Items**: Read & Write

        ## Import

        The resource does not support import.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] area: Root folder. Must be one of `Shared Queries` or `My Queries`.
        :param pulumi.Input[_builtins.str] name: The display name of the folder.
        :param pulumi.Input[_builtins.str] parent_id: The ID of the parent query folder.
        :param pulumi.Input[_builtins.str] project_id: The ID of the Project containing the folder.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: WorkitemqueryFolderArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a Work Item Query Folder in Azure DevOps.

        Folders allow you to organize queries in a hierarchy beneath either the `Shared Queries` or `My Queries` root folder (area).
        You must provide exactly one of `area` (either `Shared Queries` or `My Queries`) or `parent_id` (an existing folder's ID) when creating a folder.

        ## Example Usage

        ### Basic folder under Shared Queries

        ```python
        import pulumi
        import pulumi_azuredevops as azuredevops

        example = azuredevops.Project("example",
            name="Example Project",
            work_item_template="Agile",
            version_control="Git",
            visibility="private",
            description="Managed by Pulumi")
        team_folder = azuredevops.WorkitemqueryFolder("team_folder",
            project_id=example.id,
            name="Team",
            area="Shared Queries")
        ```

        ### Nested folder

        ```python
        import pulumi
        import pulumi_azuredevops as azuredevops

        parent = azuredevops.WorkitemqueryFolder("parent",
            project_id=example["id"],
            name="Parent",
            area="Shared Queries")
        child = azuredevops.WorkitemqueryFolder("child",
            project_id=example["id"],
            name="Child",
            parent_id=parent.id)
        ```

        ## Relevant Links

        * [Azure DevOps REST API - Work Item Query (Queries)](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/queries?view=azure-devops-rest-7.1)

        ## PAT Permissions Required

        * **Work Items**: Read & Write

        ## Import

        The resource does not support import.

        :param str resource_name: The name of the resource.
        :param WorkitemqueryFolderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WorkitemqueryFolderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 area: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 parent_id: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WorkitemqueryFolderArgs.__new__(WorkitemqueryFolderArgs)

            __props__.__dict__["area"] = area
            __props__.__dict__["name"] = name
            __props__.__dict__["parent_id"] = parent_id
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
        super(WorkitemqueryFolder, __self__).__init__(
            'azuredevops:index/workitemqueryFolder:WorkitemqueryFolder',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            area: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            parent_id: Optional[pulumi.Input[_builtins.str]] = None,
            project_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'WorkitemqueryFolder':
        """
        Get an existing WorkitemqueryFolder resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] area: Root folder. Must be one of `Shared Queries` or `My Queries`.
        :param pulumi.Input[_builtins.str] name: The display name of the folder.
        :param pulumi.Input[_builtins.str] parent_id: The ID of the parent query folder.
        :param pulumi.Input[_builtins.str] project_id: The ID of the Project containing the folder.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _WorkitemqueryFolderState.__new__(_WorkitemqueryFolderState)

        __props__.__dict__["area"] = area
        __props__.__dict__["name"] = name
        __props__.__dict__["parent_id"] = parent_id
        __props__.__dict__["project_id"] = project_id
        return WorkitemqueryFolder(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def area(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Root folder. Must be one of `Shared Queries` or `My Queries`.
        """
        return pulumi.get(self, "area")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The display name of the folder.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The ID of the parent query folder.
        """
        return pulumi.get(self, "parent_id")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the Project containing the folder.
        """
        return pulumi.get(self, "project_id")

