// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureDevOps.Inputs
{

    public sealed class BuildDefinitionJobTargetGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("demands")]
        private InputList<string>? _demands;

        /// <summary>
        /// A list of demands that represents the agent capabilities required by this build. Example: `Git`
        /// </summary>
        public InputList<string> Demands
        {
            get => _demands ?? (_demands = new InputList<string>());
            set => _demands = value;
        }

        /// <summary>
        /// A `ExecutionOptions` blocks as documented below.
        /// </summary>
        [Input("executionOptions", required: true)]
        public Input<Inputs.BuildDefinitionJobTargetExecutionOptionsGetArgs> ExecutionOptions { get; set; } = null!;

        /// <summary>
        /// The job type. Possible values: `AgentJob`, `AgentlessJob`
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public BuildDefinitionJobTargetGetArgs()
        {
        }
        public static new BuildDefinitionJobTargetGetArgs Empty => new BuildDefinitionJobTargetGetArgs();
    }
}
