// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages permissions for an Iteration (Sprint)
 *
 * > **Note** Permissions can be assigned to group principals and not to single user principals.
 *
 * ## Permission levels
 *
 * Permission for Iterations within Azure DevOps can be applied on two different levels.
 * Those levels are reflected by specifying (or omitting) values for the arguments `projectId` and `path`.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azuredevops from "@pulumi/azuredevops";
 *
 * const project = new azuredevops.Project("project", {
 *     workItemTemplate: "Agile",
 *     versionControl: "Git",
 *     visibility: "private",
 *     description: "Managed by Terraform",
 * });
 * const project-readers = project.id.apply(id => azuredevops.getGroup({
 *     projectId: id,
 *     name: "Readers",
 * }));
 * const root_permissions = new azuredevops.IterativePermissions("root-permissions", {
 *     projectId: project.id,
 *     principal: azuredevops_group["project-readers"].id,
 *     permissions: {
 *         CREATE_CHILDREN: "Deny",
 *         GENERIC_READ: "NotSet",
 *         DELETE: "Deny",
 *     },
 * });
 * const iteration_permissions = new azuredevops.IterativePermissions("iteration-permissions", {
 *     projectId: project.id,
 *     principal: azuredevops_group["project-readers"].id,
 *     path: "Iteration 1",
 *     permissions: {
 *         CREATE_CHILDREN: "Allow",
 *         GENERIC_READ: "NotSet",
 *         DELETE: "Allow",
 *     },
 * });
 * ```
 * ## Relevant Links
 *
 * * [Azure DevOps Service REST API 5.1 - Security](https://docs.microsoft.com/en-us/rest/api/azure/devops/security/?view=azure-devops-rest-5.1)
 *
 * ## PAT Permissions Required
 *
 * - **Project & Team**: vso.security_manage - Grants the ability to read, write, and manage security permissions.
 *
 * ## Import
 *
 * The resource does not support import.
 */
export class IterativePermissions extends pulumi.CustomResource {
    /**
     * Get an existing IterativePermissions resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IterativePermissionsState, opts?: pulumi.CustomResourceOptions): IterativePermissions {
        return new IterativePermissions(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'azuredevops:index/iterativePermissions:IterativePermissions';

    /**
     * Returns true if the given object is an instance of IterativePermissions.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IterativePermissions {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IterativePermissions.__pulumiType;
    }

    /**
     * The name of the branch to assign the permissions.
     */
    public readonly path!: pulumi.Output<string | undefined>;
    /**
     * the permissions to assign. The following permissions are available.
     */
    public readonly permissions!: pulumi.Output<{[key: string]: string}>;
    /**
     * The **group** principal to assign the permissions.
     */
    public readonly principal!: pulumi.Output<string>;
    /**
     * The ID of the project to assign the permissions.
     */
    public readonly projectId!: pulumi.Output<string>;
    /**
     * Replace (`true`) or merge (`false`) the permissions. Default: `true`
     */
    public readonly replace!: pulumi.Output<boolean | undefined>;

    /**
     * Create a IterativePermissions resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IterativePermissionsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IterativePermissionsArgs | IterativePermissionsState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as IterativePermissionsState | undefined;
            inputs["path"] = state ? state.path : undefined;
            inputs["permissions"] = state ? state.permissions : undefined;
            inputs["principal"] = state ? state.principal : undefined;
            inputs["projectId"] = state ? state.projectId : undefined;
            inputs["replace"] = state ? state.replace : undefined;
        } else {
            const args = argsOrState as IterativePermissionsArgs | undefined;
            if ((!args || args.permissions === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'permissions'");
            }
            if ((!args || args.principal === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'principal'");
            }
            if ((!args || args.projectId === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'projectId'");
            }
            inputs["path"] = args ? args.path : undefined;
            inputs["permissions"] = args ? args.permissions : undefined;
            inputs["principal"] = args ? args.principal : undefined;
            inputs["projectId"] = args ? args.projectId : undefined;
            inputs["replace"] = args ? args.replace : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(IterativePermissions.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IterativePermissions resources.
 */
export interface IterativePermissionsState {
    /**
     * The name of the branch to assign the permissions.
     */
    readonly path?: pulumi.Input<string>;
    /**
     * the permissions to assign. The following permissions are available.
     */
    readonly permissions?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The **group** principal to assign the permissions.
     */
    readonly principal?: pulumi.Input<string>;
    /**
     * The ID of the project to assign the permissions.
     */
    readonly projectId?: pulumi.Input<string>;
    /**
     * Replace (`true`) or merge (`false`) the permissions. Default: `true`
     */
    readonly replace?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a IterativePermissions resource.
 */
export interface IterativePermissionsArgs {
    /**
     * The name of the branch to assign the permissions.
     */
    readonly path?: pulumi.Input<string>;
    /**
     * the permissions to assign. The following permissions are available.
     */
    readonly permissions: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The **group** principal to assign the permissions.
     */
    readonly principal: pulumi.Input<string>;
    /**
     * The ID of the project to assign the permissions.
     */
    readonly projectId: pulumi.Input<string>;
    /**
     * Replace (`true`) or merge (`false`) the permissions. Default: `true`
     */
    readonly replace?: pulumi.Input<boolean>;
}
