// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a Jenkins service endpoint within Azure DevOps, which can be used as a resource in YAML pipelines to connect to a Jenkins instance.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azuredevops from "@pulumi/azuredevops";
 *
 * const example = new azuredevops.Project("example", {
 *     name: "Example Project",
 *     visibility: "private",
 *     versionControl: "Git",
 *     workItemTemplate: "Agile",
 *     description: "Managed by Pulumi",
 * });
 * const exampleServiceendpointJenkins = new azuredevops.ServiceendpointJenkins("example", {
 *     projectId: example.id,
 *     serviceEndpointName: "jenkins-example",
 *     description: "Service Endpoint for 'Jenkins' (Managed by Terraform)",
 *     url: "https://example.com",
 *     acceptUntrustedCerts: false,
 *     username: "username",
 *     password: "password",
 * });
 * ```
 *
 * ## Import
 *
 * Azure DevOps Jenkins Service Endpoint can be imported using the `projectId/id` or `projectName/id`, e.g.
 *
 * ```sh
 * $ pulumi import azuredevops:index/serviceendpointJenkins:ServiceendpointJenkins example projectName/00000000-0000-0000-0000-000000000000
 * ```
 */
export class ServiceendpointJenkins extends pulumi.CustomResource {
    /**
     * Get an existing ServiceendpointJenkins resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceendpointJenkinsState, opts?: pulumi.CustomResourceOptions): ServiceendpointJenkins {
        return new ServiceendpointJenkins(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'azuredevops:index/serviceendpointJenkins:ServiceendpointJenkins';

    /**
     * Returns true if the given object is an instance of ServiceendpointJenkins.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceendpointJenkins {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceendpointJenkins.__pulumiType;
    }

    /**
     * Allows the Jenkins clients to accept self-signed SSL server certificates. Defaults to `false.`
     */
    declare public readonly acceptUntrustedCerts: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly authorization: pulumi.Output<{[key: string]: string}>;
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The Service Endpoint password to authenticate at the Jenkins Instance.
     */
    declare public readonly password: pulumi.Output<string>;
    /**
     * The ID of the project. Changing this forces a new Service Connection Jenkins to be created.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * The name of the service endpoint. Changing this forces a new Service Connection Jenkins to be created.
     */
    declare public readonly serviceEndpointName: pulumi.Output<string>;
    /**
     * The Service Endpoint url.
     */
    declare public readonly url: pulumi.Output<string>;
    /**
     * The Service Endpoint username to authenticate at the Jenkins Instance.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a ServiceendpointJenkins resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceendpointJenkinsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceendpointJenkinsArgs | ServiceendpointJenkinsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceendpointJenkinsState | undefined;
            resourceInputs["acceptUntrustedCerts"] = state?.acceptUntrustedCerts;
            resourceInputs["authorization"] = state?.authorization;
            resourceInputs["description"] = state?.description;
            resourceInputs["password"] = state?.password;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["serviceEndpointName"] = state?.serviceEndpointName;
            resourceInputs["url"] = state?.url;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as ServiceendpointJenkinsArgs | undefined;
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.serviceEndpointName === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceEndpointName'");
            }
            if (args?.url === undefined && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["acceptUntrustedCerts"] = args?.acceptUntrustedCerts;
            resourceInputs["description"] = args?.description;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["serviceEndpointName"] = args?.serviceEndpointName;
            resourceInputs["url"] = args?.url;
            resourceInputs["username"] = args?.username;
            resourceInputs["authorization"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ServiceendpointJenkins.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServiceendpointJenkins resources.
 */
export interface ServiceendpointJenkinsState {
    /**
     * Allows the Jenkins clients to accept self-signed SSL server certificates. Defaults to `false.`
     */
    acceptUntrustedCerts?: pulumi.Input<boolean>;
    authorization?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    description?: pulumi.Input<string>;
    /**
     * The Service Endpoint password to authenticate at the Jenkins Instance.
     */
    password?: pulumi.Input<string>;
    /**
     * The ID of the project. Changing this forces a new Service Connection Jenkins to be created.
     */
    projectId?: pulumi.Input<string>;
    /**
     * The name of the service endpoint. Changing this forces a new Service Connection Jenkins to be created.
     */
    serviceEndpointName?: pulumi.Input<string>;
    /**
     * The Service Endpoint url.
     */
    url?: pulumi.Input<string>;
    /**
     * The Service Endpoint username to authenticate at the Jenkins Instance.
     */
    username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ServiceendpointJenkins resource.
 */
export interface ServiceendpointJenkinsArgs {
    /**
     * Allows the Jenkins clients to accept self-signed SSL server certificates. Defaults to `false.`
     */
    acceptUntrustedCerts?: pulumi.Input<boolean>;
    description?: pulumi.Input<string>;
    /**
     * The Service Endpoint password to authenticate at the Jenkins Instance.
     */
    password: pulumi.Input<string>;
    /**
     * The ID of the project. Changing this forces a new Service Connection Jenkins to be created.
     */
    projectId: pulumi.Input<string>;
    /**
     * The name of the service endpoint. Changing this forces a new Service Connection Jenkins to be created.
     */
    serviceEndpointName: pulumi.Input<string>;
    /**
     * The Service Endpoint url.
     */
    url: pulumi.Input<string>;
    /**
     * The Service Endpoint username to authenticate at the Jenkins Instance.
     */
    username: pulumi.Input<string>;
}
